name: shartflix
description: "Shartflix"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  go_router: ^16.0.0
  bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.4
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

  file_picker: ^10.2.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  firebase_core: ^3.15.2
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10
  flutter_native_splash: ^2.4.6
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0


flutter_launcher_icons:
  ios: true
  image_path: "assets/images/png_images/sinflix_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  android: true

flutter_native_splash:
  color: "#000000"   # kesinlikle bu olmalı
  image: "assets/images/png_images/sinflix_logo-splash.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/png_images/sinflix_logo-splash.png"
    icon_background_color: "#000000"
    icon_background_color_dark: "#000000"
    image_dark: "assets/images/png_images/sinflix_logo-splash.png"

  
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/png_images/
    - assets/icons/svg_icons/
    - assets/icons/png_icons/
    - assets/images/
    - assets/translations/

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/euclid_circular_a_light.ttf
          weight: 300
        - asset: assets/fonts/euclid_circular_a_regular.ttf
          weight: 400
        - asset: assets/fonts/euclid_circular_a_medium.ttf
          weight: 500
        - asset: assets/fonts/euclid_circular_a_semiBold.ttf
          weight: 600
        - asset: assets/fonts/euclid_circular_a_bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/generated/